export const donations = [
  {name: "dari", amount: 10},
  {name: "dev", amount: 20},
  {name: "John", amount: 30},
  {name: "Doe", amount: 40},
  {name: "John", amount: 50},
  {name: "Smith", amount: 100},
  {name: "John", amount: 200},
  {name: "Doe", amount: 300},
  {name: "John", amount: 400},
  {name: "Smith", amount: 500},
  {name: "Page", amount: 150},
  {name: "Carter", amount: 160},
  {name: "John", amount: 170},
  {name: "Doe", amount: 180},
  {name: "John", amount: 190},
  {name: "Smith", amount: 20},
]