export const donations = [
  {name: "dari", amount: 10, imageUrl: './images/person1.png'},
  {name: "dev", amount: 20, imageUrl: './images/person2.png'},
  {name: "John", amount: 30, imageUrl: './images/person3.png'},
  {name: "Doe", amount: 40, imageUrl: './images/person4.png'},
  {name: "John", amount: 50, imageUrl: './images/person5.png'},
  {name: "Smith", amount: 100, imageUrl: './images/person1.png'},
  {name: "John", amount: 200, imageUrl: './images/person2.png'},
  {name: "Doe", amount: 300, imageUrl: './images/person3.png'},
  {name: "John", amount: 400, imageUrl: './images/person4.png'},
  {name: "Smith", amount: 500, imageUrl: './images/person5.png'},
  {name: "Page", amount: 150, imageUrl: './images/person1.png'},
  {name: "Carter", amount: 160, imageUrl: './images/person2.png'},
  {name: "John", amount: 170, imageUrl: './images/person3.png'},
  {name: "Doe", amount: 180, imageUrl: './images/person4.png'},
  {name: "John", amount: 190, imageUrl: './images/person5.png'},
  {name: "Smith", amount: 20, imageUrl: './images/person1.png'},
]